# Huckleberry Sleep Notification Automation Examples
#
# These automations demonstrate how to create notifications with chronometer
# for baby sleep tracking, including actionable notifications to control sleep.

# ============================================================================
# Example 1: Basic Sleep Notification with Chronometer
# ============================================================================
# This automation sends a persistent notification when sleep starts and
# clears it when sleep stops. The notification shows a live chronometer.

- alias: "Baby Sleep Notification"
  description: "Show notification with chronometer when baby is sleeping"
  trigger:
    # Trigger when sleep status changes
    - platform: state
      entity_id: binary_sensor.your_child_name_sleep_status
      to: "on"
      id: sleep_started
    - platform: state
      entity_id: binary_sensor.your_child_name_sleep_status
      to: "off"
      id: sleep_stopped
  action:
    - choose:
        # When sleep starts - send notification
        - conditions:
            - condition: trigger
              id: sleep_started
          sequence:
            - service: notify.mobile_app_your_phone
              data:
                title: "Baby Sleep"
                message: >
                  Sleep since {{ (state_attr('binary_sensor.your_child_name_sleep_status', 'timer_start_time') | int | timestamp_custom('%H:%M', true)) }}
                data:
                  # Chronometer shows live elapsed time
                  chronometer: true
                  # Use the timer_start_time attribute (Unix timestamp in seconds)
                  when: "{{ state_attr('binary_sensor.your_child_name_sleep_status', 'timer_start_time') }}"
                  notification_icon: "mdi:sleep"
                  # Tag ensures the notification can be updated/cleared
                  tag: "baby_sleep"
                  # Persistent notification stays until manually dismissed
                  persistent: true
                  # Action buttons to control sleep
                  actions:
                    - action: "STOP_SLEEP"
                      title: "Stop"
                    - action: "PAUSE_SLEEP"
                      title: "Pause"
        # When sleep stops - clear notification
        - conditions:
            - condition: trigger
              id: sleep_stopped
          sequence:
            - service: notify.mobile_app_your_phone
              data:
                message: "clear_notification"
                data:
                  tag: "baby_sleep"

# ============================================================================
# Example 2: Handle Notification Actions (Stop/Pause)
# ============================================================================
# This automation responds to the action buttons in the notification

- alias: "Handle Baby Sleep Notification Actions"
  description: "Handle stop and pause actions from sleep notification"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "STOP_SLEEP"
      id: stop_sleep
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "PAUSE_SLEEP"
      id: pause_sleep
  action:
    - choose:
        # Stop sleep action
        - conditions:
            - condition: trigger
              id: stop_sleep
          sequence:
            - service: huckleberry.complete_sleep
              target:
                # Use device_id for the child (automatically created by integration)
                device_id: YOUR_CHILD_DEVICE_ID
        # Pause sleep action
        - conditions:
            - condition: trigger
              id: pause_sleep
          sequence:
            - service: huckleberry.pause_sleep
              target:
                device_id: YOUR_CHILD_DEVICE_ID

# ============================================================================
# Example 3: Advanced - Sleep with Pause/Resume Notification
# ============================================================================
# This shows different messages for active vs paused sleep

- alias: "Advanced Baby Sleep Notification"
  description: "Show different notifications for active/paused sleep"
  trigger:
    - platform: state
      entity_id: binary_sensor.your_child_name_sleep_status
  action:
    - choose:
        # Active sleep - show chronometer
        - conditions:
            - condition: state
              entity_id: binary_sensor.your_child_name_sleep_status
              state: "on"
          sequence:
            - service: notify.mobile_app_your_phone
              data:
                title: "Baby Sleeping ðŸ˜´"
                message: >
                  Started at {{ (state_attr('binary_sensor.your_child_name_sleep_status', 'timer_start_time') | int | timestamp_custom('%H:%M', true)) }}
                data:
                  chronometer: true
                  when: "{{ state_attr('binary_sensor.your_child_name_sleep_status', 'timer_start_time') }}"
                  notification_icon: "mdi:sleep"
                  tag: "baby_sleep"
                  persistent: true
                  color: "#4CAF50"
                  actions:
                    - action: "COMPLETE_SLEEP"
                      title: "Complete"
                      icon: "sfsymbols:checkmark.circle"
                    - action: "PAUSE_SLEEP"
                      title: "Pause"
                      icon: "sfsymbols:pause.circle"
                    - action: "CANCEL_SLEEP"
                      title: "Cancel"
                      icon: "sfsymbols:xmark.circle"
        # Sleep stopped - clear notification
        - conditions:
            - condition: state
              entity_id: binary_sensor.your_child_name_sleep_status
              state: "off"
          sequence:
            - service: notify.mobile_app_your_phone
              data:
                message: "clear_notification"
                data:
                  tag: "baby_sleep"
            # Optional: Send summary of last sleep
            - service: notify.mobile_app_your_phone
              data:
                title: "Sleep Complete"
                message: >
                  Duration: {{ (state_attr('binary_sensor.your_child_name_sleep_status', 'last_sleep_duration_seconds') | int / 60) | round(0) }} minutes
                data:
                  notification_icon: "mdi:sleep-off"

# ============================================================================
# Example 4: Complete Action Handler (Stop, Pause, Resume, Cancel)
# ============================================================================

- alias: "Complete Baby Sleep Action Handler"
  description: "Handle all sleep notification actions"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "COMPLETE_SLEEP"
      id: complete
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "PAUSE_SLEEP"
      id: pause
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "RESUME_SLEEP"
      id: resume
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "CANCEL_SLEEP"
      id: cancel
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: complete
          sequence:
            - service: huckleberry.complete_sleep
              target:
                device_id: YOUR_CHILD_DEVICE_ID
        - conditions:
            - condition: trigger
              id: pause
          sequence:
            - service: huckleberry.pause_sleep
              target:
                device_id: YOUR_CHILD_DEVICE_ID
            # Update notification to show paused state
            - service: notify.mobile_app_your_phone
              data:
                title: "Baby Sleep Paused â¸ï¸"
                message: "Sleep session paused"
                data:
                  tag: "baby_sleep"
                  persistent: true
                  actions:
                    - action: "RESUME_SLEEP"
                      title: "Resume"
                    - action: "CANCEL_SLEEP"
                      title: "Cancel"
        - conditions:
            - condition: trigger
              id: resume
          sequence:
            - service: huckleberry.resume_sleep
              target:
                device_id: YOUR_CHILD_DEVICE_ID
        - conditions:
            - condition: trigger
              id: cancel
          sequence:
            - service: huckleberry.cancel_sleep
              target:
                device_id: YOUR_CHILD_DEVICE_ID

# ============================================================================
# Example 5: Multi-Child Support
# ============================================================================
# If you have multiple children, use this pattern

- alias: "Multi-Child Sleep Notifications"
  description: "Handle sleep notifications for multiple children"
  trigger:
    # Add trigger for each child
    - platform: state
      entity_id: binary_sensor.child1_name_sleep_status
      to: "on"
      id: child1_start
    - platform: state
      entity_id: binary_sensor.child1_name_sleep_status
      to: "off"
      id: child1_stop
    - platform: state
      entity_id: binary_sensor.child2_name_sleep_status
      to: "on"
      id: child2_start
    - platform: state
      entity_id: binary_sensor.child2_name_sleep_status
      to: "off"
      id: child2_stop
  action:
    - choose:
        # Child 1 started sleeping
        - conditions:
            - condition: trigger
              id: child1_start
          sequence:
            - service: notify.mobile_app_your_phone
              data:
                title: "Child 1 Sleeping"
                message: >
                  Sleep since {{ (state_attr('binary_sensor.child1_name_sleep_status', 'timer_start_time') | int | timestamp_custom('%H:%M', true)) }}
                data:
                  chronometer: true
                  when: "{{ state_attr('binary_sensor.child1_name_sleep_status', 'timer_start_time') }}"
                  tag: "baby_sleep_child1"
                  notification_icon: "mdi:sleep"
                  actions:
                    - action: "STOP_SLEEP_CHILD1"
                      title: "Stop"
        # Child 1 stopped sleeping
        - conditions:
            - condition: trigger
              id: child1_stop
          sequence:
            - service: notify.mobile_app_your_phone
              data:
                message: "clear_notification"
                data:
                  tag: "baby_sleep_child1"
        # Repeat for additional children...
# ============================================================================
# CONFIGURATION NOTES:
# ============================================================================
#
# 1. Replace "your_child_name" with your actual child's name (lowercase, underscores)
#    Example: binary_sensor.emma_sleep_status
#
# 2. Replace "YOUR_CHILD_DEVICE_ID" with the actual device ID from Home Assistant
#    You can find this in: Settings â†’ Devices & Services â†’ Huckleberry â†’ Click on child device
#    Or use the device picker in the automation UI
#
# 3. Replace "mobile_app_your_phone" with your actual mobile app notify service
#    Check available services: Developer Tools â†’ Services â†’ Filter by "notify."
#
# 4. The chronometer will show elapsed time since timer_start_time
#    The timer_start_time attribute is automatically provided by the integration
#
# 5. Notification actions (buttons) are device-specific:
#    - iOS: Uses mobile_app_notification_action event
#    - Android: May need adjustment based on notification settings
#
# 6. For the "when" parameter, use the timer_start_time attribute:
#    {{ state_attr('binary_sensor.your_child_name_sleep_status', 'timer_start_time') }}
#    This is automatically calculated from timerStartTime (milliseconds â†’ seconds)
#
# ============================================================================
